전 날 수업 내용에 대해 복습하고 정리한 내용으로 TIL 작성함.
github에 push 하려는데 레퍼런스 오류 발생

```
error: 레퍼런스를 'git@github.com:'에 푸시하는데 실패했습니다
힌트: 현재 브랜치의 끝이 리모트 브랜치보다 뒤에 있으므로 업데이트가
힌트: 거부되었습니다. 푸시하기 전에 ('git pull ...' 등 명령으로) 리모트
힌트: 변경 사항을 포함하십시오.
힌트: 자세한 정보는 'git push --help'의 "Note about fast-forwards' 부분을
힌트: 참고하십시오.
```

그 동안 잘 해왔는데 느닷없이 오류 발생하니 당황스럽네.
약 40분간 구글링하면서 이것저것 시도해봤으나 다 실패.

원인은 내 로컬 저장소에서 작업한 것과 원격 저장소에 있는 내용이 더 추가되어 있기 때문이라나? 

그런데 따로 건든게 없었기 때문에 이 설명이 납득가지 않았다.

어쨋든 차이를 없애기 위해 원격 저장소에 있는 것을 다시 pull 해와야 한다는데 pull 할 내용이 없었음.

그래서 강제 push 시키기로 결정함.
```
git push -u origin master --force
```

강제 PUSH 하면 이전 commit 들이 삭제된다는데 지극히 개인적인 기록물이니 크게 상관 없다고 판단했다.

결국 억지로 github repo 에 있는 내용을 local과 동일하게 만들었고, 이후부터는 해당 오류 발생하지 않았음.

해결 되어서 기쁘긴 한데 뭘 제대로 이해하고 한게 아니어서 많이 찝찝하다.
따로 메모해뒀다가 공부해야겠다.



